//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string a_id { get; set; }
        public string a_name { get; set; }
        public string a_mail { get; set; }
    
        public virtual User_DB User_DB { get; set; }
    }
}
