//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_DB
    {
        public int f_id { get; set; }
        public string feedback { get; set; }
        public string c_id { get; set; }
        public string i_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item_DB Item_DB { get; set; }
    }
}
