//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_DB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_DB()
        {
            this.Feedback_DB = new HashSet<Feedback_DB>();
            this.order_details = new HashSet<order_details>();
        }
    
        public string I_id { get; set; }
        public string I_name { get; set; }
        public string I_description { get; set; }
        public string cc_id { get; set; }
        public int i_cost { get; set; }
        public int i_discount { get; set; }
        public string i_status { get; set; }
        public int i_quantity { get; set; }
        public string i_company { get; set; }
        public string i_imagepath { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_DB> Feedback_DB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
