//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int o_id { get; set; }
        public string i_id { get; set; }
        public string cc_id { get; set; }
        public string c_id { get; set; }
        public string o_status { get; set; }
        public string o_date { get; set; }
        public string o_cost { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Item_DB Item_DB { get; set; }
    }
}
